imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    date_format: d/m/Y
    app.site.url: http://longchamp-roller-team.com
    app.site.name: "Longchamp Roller Team"
    app.site.webmaster.email: alexandre.seiller92@gmail.com
    app.social.facebook: http://www.facebook.com/pages/Longchamp-Roller-Team/355637923045
    app.social.twitter:
    app.social.vimeo: http://vimeo.com/user9201223
    app.adhesion.debut: "01/10/2012"
    app.adhesion.fin: "30/09/2013"
    knp_limit_per_page: 5

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  fr
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      baseUrl: %app.site.url%
      sitename: %app.site.name%
      socialFacebook: %app.social.facebook%
      socialTwitter: %app.social.twitter%
      socialVimeo: %app.social.vimeo%
      adhesionDebut: %app.adhesion.debut%
      adhesionFin: %app.adhesion.fin%

services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Lrt\UserBundle\Entity\User
    group:
        group_class: Lrt\UserBundle\Entity\Group
    from_email:
        address: "%mailer_sender_address%"
        sender_name: "%mailer_sender_name%"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool: { type: memory }

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [CMSBundle]
        directories: ["%kernel.root_dir%/../src"]

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: false
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig