imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    host:      localhost
    username:  null
    password:  null
    port:      25

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/LRT.sqlite"
        logging:  true
       
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug