parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     longcha1_db
    database_user:     longcha1_root
    database_password: J@AGKFXz_.vn

    mailer_transport:  smtp
    mailer_host:       mail.longchamp-roller-team.com
    mailer_user:       webmaster@longchamp-roller-team.com
    mailer_password:   synergie92
    mailer_port:       26

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    mailer_sender_address: webmaster@longchamp-roller-team.com
    mailer_sender_name: Longchamp Roller Team

    cdn_server_video: http://video.longchamp-roller-team.com
